name: remote ssh command

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy commits
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          echo "Clone Git Repository"
          git clone https://github.com/fjnalta/ezlife.git
          echo "Change working directory"
          cd ezlife
          echo "Install node modules"
          npm install --save
          echo "(Re)Start node app"
          pm2 restart app.js
